# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterApp
pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git', :tag => '2.4.0'
  target 'TwitterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterAppUITests' do
    # Pods for testing
  end

end
